//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D365BCWebServiceClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingUnitsOfMeasure?tenant=msweua6461t47719790&a" +
            "id=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingUnitsOfMeasure_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingUnitsOfMeasure_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/purchaseDocumentLines?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_purchaseDocumentLines_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_purchaseDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingPaymentTerms?tenant=msweua6461t47719790&aid" +
            "=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingPaymentTerms_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingPaymentTerms_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/InvoiceDocument?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_InvoiceDocument_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_InvoiceDocument_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingCustomers?tenant=msweua6461t47719790&aid=FI" +
            "N")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingCustomers_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingCustomers_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingSyncServicesSetting?tenant=msweua6461t47719" +
            "790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingSyncServicesSetting_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingSyncServicesSetting_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/ExcelTemplateBalanceSheet?tenant=msweua6461t47719790&aid=F" +
            "IN")]
        public string D365BCWebServiceClient_BCWS_ExcelTemplateBalanceSheet_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_ExcelTemplateBalanceSheet_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Job_Planning_Lines?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_Job_Planning_Lines_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Job_Planning_Lines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingSalesInvoices?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingSalesInvoices_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingSalesInvoices_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_Job_Profitability?tenant=msweua6461t47719790&aid=" +
            "FIN")]
        public string D365BCWebServiceClient_BCWS_Power_BI_Job_Profitability_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_Job_Profitability_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowItems?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_workflowItems_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowItems_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingPaymentMethods?tenant=msweua6461t47719790&a" +
            "id=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingPaymentMethods_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingPaymentMethods_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Customer?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_Customer_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Customer_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/SystemService?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_SystemService {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/AccountantPortalUserTasks?tenant=msweua6461t47719790&aid=F" +
            "IN")]
        public string D365BCWebServiceClient_BCWS_AccountantPortalUserTasks_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_AccountantPortalUserTasks_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowGenJournalLines?tenant=msweua6461t47719790&aid=FIN" +
            "")]
        public string D365BCWebServiceClient_BCWS_workflowGenJournalLines_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowGenJournalLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/salesDocuments?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_salesDocuments_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_salesDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Piano_dei_conti?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_Piano_dei_conti_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Piano_dei_conti_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingAttachments?tenant=msweua6461t47719790&aid=" +
            "FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingAttachments_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingAttachments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/UserTaskSetComplete?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_UserTaskSetComplete_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_UserTaskSetComplete_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingEmailPreview?tenant=msweua6461t47719790&aid" +
            "=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingEmailPreview_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingEmailPreview_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowSalesDocumentLines?tenant=msweua6461t47719790&aid=" +
            "FIN")]
        public string D365BCWebServiceClient_BCWS_workflowSalesDocumentLines_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowSalesDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingLanguages?tenant=msweua6461t47719790&aid=FI" +
            "N")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingLanguages_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingLanguages_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/ExcelTemplateCashFlowStatement?tenant=msweua6461t47719790&" +
            "aid=FIN")]
        public string D365BCWebServiceClient_BCWS_ExcelTemplateCashFlowStatement_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_ExcelTemplateCashFlowStatement_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Job_Task_Lines?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_Job_Task_Lines_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Job_Task_Lines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingSalesInvoiceOverview?tenant=msweua6461t4771" +
            "9790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingSalesInvoiceOverview_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingSalesInvoiceOverview_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_WorkDate_Calc?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_Power_BI_WorkDate_Calc__Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_WorkDate_Calc__Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingTaxRates?tenant=msweua6461t47719790&aid=FIN" +
            "")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingTaxRates_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingTaxRates_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Codeunit/ExchangeServiceSetup?tenant=msweua6461t47719790&aid=FI" +
            "N")]
        public string D365BCWebServiceClient_BCWS_ExchangeServiceSetup {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_ExchangeServiceSetup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_Sales_Pipeline?tenant=msweua6461t47719790&aid=FIN" +
            "")]
        public string D365BCWebServiceClient_BCWS_Power_BI_Sales_Pipeline_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_Sales_Pipeline_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/ExcelTemplateAgedAccountsPayable?tenant=msweua6461t4771979" +
            "0&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_ExcelTemplateAgedAccountsPayable_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_ExcelTemplateAgedAccountsPayable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/AccountantPortalFinanceCues?tenant=msweua6461t47719790&aid" +
            "=FIN")]
        public string D365BCWebServiceClient_BCWS_AccountantPortalFinanceCues_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_AccountantPortalFinanceCues_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/purchaseDocuments?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_purchaseDocuments_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_purchaseDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowPurchaseDocumentLines?tenant=msweua6461t47719790&a" +
            "id=FIN")]
        public string D365BCWebServiceClient_BCWS_workflowPurchaseDocumentLines_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowPurchaseDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/AccountantPortalActivityCues?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_AccountantPortalActivityCues_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_AccountantPortalActivityCues_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowWebhookSubscriptions?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_workflowWebhookSubscriptions_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowWebhookSubscriptions_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/C2Graph?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_C2Graph_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_C2Graph_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_Aged_Inventory_Chart?tenant=msweua6461t47719790&a" +
            "id=FIN")]
        public string D365BCWebServiceClient_BCWS_Power_BI_Aged_Inventory_Chart_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_Aged_Inventory_Chart_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Codeunit/CompanySetupService?tenant=msweua6461t47719790&aid=FIN" +
            "")]
        public string D365BCWebServiceClient_BCWS_CompanySetupService {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_CompanySetupService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Codeunit/WorkflowActionResponse?tenant=msweua6461t47719790&aid=" +
            "FIN")]
        public string D365BCWebServiceClient_BCWS_WorkflowActionResponse {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_WorkflowActionResponse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowCustomers?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_workflowCustomers_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowCustomers_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingKPIs?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingKPIs_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingKPIs_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingVATSetup?tenant=msweua6461t47719790&aid=FIN" +
            "")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingVATSetup_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingVATSetup_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/ExcelTemplateRetainedEarnings?tenant=msweua6461t47719790&a" +
            "id=FIN")]
        public string D365BCWebServiceClient_BCWS_ExcelTemplateRetainedEarnings_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_ExcelTemplateRetainedEarnings_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingItems?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingItems_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingItems_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/powerbifinance?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_powerbifinance_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_powerbifinance_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Codeunit/EncryptedKeyValue?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_EncryptedKeyValue {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_EncryptedKeyValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowPurchaseDocuments?tenant=msweua6461t47719790&aid=F" +
            "IN")]
        public string D365BCWebServiceClient_BCWS_workflowPurchaseDocuments_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowPurchaseDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/InvoiceReminder?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_InvoiceReminder_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_InvoiceReminder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingSMTPMailSetup?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingSMTPMailSetup_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingSMTPMailSetup_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_Aged_Acc_Payable?tenant=msweua6461t47719790&aid=F" +
            "IN")]
        public string D365BCWebServiceClient_BCWS_Power_BI_Aged_Acc__Payable_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_Aged_Acc__Payable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingTaxAreas?tenant=msweua6461t47719790&aid=FIN" +
            "")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingTaxAreas_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingTaxAreas_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingPDFs?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingPDFs_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingPDFs_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingCountryRegion?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingCountryRegion_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingCountryRegion_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingQBOSyncAuth?tenant=msweua6461t47719790&aid=" +
            "FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingQBOSyncAuth_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingQBOSyncAuth_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingTestMail?tenant=msweua6461t47719790&aid=FIN" +
            "")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingTestMail_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingTestMail_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_Report_Labels?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_Power_BI_Report_Labels_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_Report_Labels_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowSalesDocuments?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_workflowSalesDocuments_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowSalesDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingContacts?tenant=msweua6461t47719790&aid=FIN" +
            "")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingContacts_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingContacts_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingTaxGroups?tenant=msweua6461t47719790&aid=FI" +
            "N")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingTaxGroups_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingTaxGroups_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_Top_5_Opportunities?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_Power_BI_Top_5_Opportunities_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_Top_5_Opportunities_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/salesDocumentLines?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_salesDocumentLines_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_salesDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingGeneralSettings?tenant=msweua6461t47719790&" +
            "aid=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingGeneralSettings_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingGeneralSettings_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingSalesQuotes?tenant=msweua6461t47719790&aid=" +
            "FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingSalesQuotes_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingSalesQuotes_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/ExcelTemplateViewCompanyInformation?tenant=msweua6461t4771" +
            "9790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_ExcelTemplateViewCompanyInformation_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_ExcelTemplateViewCompanyInformation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingEmailSetting?tenant=msweua6461t47719790&aid" +
            "=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingEmailSetting_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingEmailSetting_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingExportInvoices?tenant=msweua6461t47719790&a" +
            "id=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingExportInvoices_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingExportInvoices_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowGenJournalBatches?tenant=msweua6461t47719790&aid=F" +
            "IN")]
        public string D365BCWebServiceClient_BCWS_workflowGenJournalBatches_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowGenJournalBatches_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_Job_Act_v_Budg_Price?tenant=msweua6461t47719790&a" +
            "id=FIN")]
        public string D365BCWebServiceClient_BCWS_Power_BI_Job_Act__v__Budg__Price_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_Job_Act__v__Budg__Price_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/workflowVendors?tenant=msweua6461t47719790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_workflowVendors_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_workflowVendors_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/ExcelTemplateIncomeStatement?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_ExcelTemplateIncomeStatement_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_ExcelTemplateIncomeStatement_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/ExcelTemplateTrialBalance?tenant=msweua6461t47719790&aid=F" +
            "IN")]
        public string D365BCWebServiceClient_BCWS_ExcelTemplateTrialBalance_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_ExcelTemplateTrialBalance_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/ExcelTemplateAgedAccountsReceivable?tenant=msweua6461t4771" +
            "9790&aid=FIN")]
        public string D365BCWebServiceClient_BCWS_ExcelTemplateAgedAccountsReceivable_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_ExcelTemplateAgedAccountsReceivable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_Aged_Acc_Receivable?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_Power_BI_Aged_Acc__Receivable_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_Aged_Acc__Receivable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/nativeInvoicingSalesTaxSetup?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_nativeInvoicingSalesTaxSetup_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_nativeInvoicingSalesTaxSetup_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v1.0/194e87bd-73c6-43c6-95d7-1ca48985db5" +
            "e/WS/CRONUS%20IT/Page/Power_BI_Job_Act_v_Budg_Cost?tenant=msweua6461t47719790&ai" +
            "d=FIN")]
        public string D365BCWebServiceClient_BCWS_Power_BI_Job_Act__v__Budg__Cost_Service {
            get {
                return ((string)(this["D365BCWebServiceClient_BCWS_Power_BI_Job_Act__v__Budg__Cost_Service"]));
            }
        }
    }
}
